"""
PostToolUse hook — regenerates the File Inventory section of claude-structure-docs.md
whenever a file inside .claude/ is created or modified.

Also runnable manually:
    python .claude/hooks/update_claude_docs.py --regenerate
"""
import json
import sys
import re
from pathlib import Path
from datetime import datetime

DOCS_FILE = Path("claude-structure-docs.md")
CLAUDE_DIR = Path(".claude")

INVENTORY_START = "<!-- CLAUDE_INVENTORY_START: DO NOT EDIT BELOW — auto-generated by .claude/hooks/update_claude_docs.py -->"
INVENTORY_END = "<!-- CLAUDE_INVENTORY_END: DO NOT EDIT ABOVE -->"

# ── Helpers ──────────────────────────────────────────────────────────────────

def get_frontmatter_field(file_path: Path, field: str) -> str:
    """Extract a single field value from YAML frontmatter of a Markdown file."""
    try:
        content = file_path.read_text(encoding="utf-8", errors="ignore")
        if not content.startswith("---"):
            return ""
        end = content.find("---", 3)
        if end < 0:
            return ""
        frontmatter = content[3:end]
        for line in frontmatter.splitlines():
            if line.startswith(f"{field}:"):
                value = line[len(field) + 1:].strip().strip('"').strip("'")
                # Trim multi-line descriptions at first newline or <example> tag
                value = re.split(r"\n|<example>", value)[0].strip()
                if len(value) > 110:
                    value = value[:110] + "…"
                return value
    except Exception:
        pass
    return ""


def get_settings_summary(settings_path: Path) -> dict:
    """Parse settings.json and return counts of allow/deny rules and hook events."""
    try:
        data = json.loads(settings_path.read_text(encoding="utf-8"))
        permissions = data.get("permissions", {})
        hooks = data.get("hooks", {})
        allow_count = len(permissions.get("allow", []))
        deny_count = len(permissions.get("deny", []))
        hook_count = sum(
            len(h_list)
            for event_list in hooks.values()
            for entry in event_list
            for h_list in [entry.get("hooks", [])]
        )
        events = list(hooks.keys())
        return {
            "allow": allow_count,
            "deny": deny_count,
            "hooks": hook_count,
            "events": events,
        }
    except Exception:
        return {}


def file_line_count(path: Path) -> int:
    try:
        return len(path.read_text(encoding="utf-8", errors="ignore").splitlines())
    except Exception:
        return 0


# ── Inventory Builder ─────────────────────────────────────────────────────────

def build_inventory() -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = []
    lines.append("## File Inventory (Auto-Generated)")
    lines.append("")
    lines.append(f"*Last updated: {now}*")
    lines.append("")

    if not CLAUDE_DIR.exists():
        lines.append("*`.claude/` directory not found.*")
        return "\n".join(lines)

    # ── settings.json ────────────────────────────────────────────────────────
    settings_path = CLAUDE_DIR / "settings.json"
    lines.append("### settings.json")
    lines.append("")
    if settings_path.exists():
        summary = get_settings_summary(settings_path)
        lines.append("| Key | Value |")
        lines.append("|---|---|")
        lines.append(f"| Allow rules | {summary.get('allow', '?')} bash commands pre-approved |")
        lines.append(f"| Deny rules | {summary.get('deny', '?')} commands blocked |")
        lines.append(f"| Hook events wired | {', '.join(summary.get('events', []))} |")
        lines.append(f"| Total hook scripts wired | {summary.get('hooks', '?')} |")
    else:
        lines.append("*Not found*")
    lines.append("")

    # ── Commands ─────────────────────────────────────────────────────────────
    commands_dir = CLAUDE_DIR / "commands"
    lines.append("### Slash Commands")
    lines.append("")
    commands = sorted(commands_dir.glob("*.md")) if commands_dir.exists() else []
    if commands:
        lines.append("| Command | Description | File |")
        lines.append("|---|---|---|")
        for f in commands:
            desc = get_frontmatter_field(f, "description") or "*no description*"
            hint = get_frontmatter_field(f, "argument-hint")
            cmd = f"/{f.stem}"
            if hint:
                cmd += f" `{hint}`"
            lines.append(f"| `{cmd}` | {desc} | [{f.name}](.claude/commands/{f.name}) |")
    else:
        lines.append("*No commands found in `.claude/commands/`*")
    lines.append("")

    # ── Agents ───────────────────────────────────────────────────────────────
    agents_dir = CLAUDE_DIR / "agents"
    lines.append("### Agents")
    lines.append("")
    agents = sorted(agents_dir.glob("*.md")) if agents_dir.exists() else []
    if agents:
        lines.append("| Agent | Description | Model | Color | File |")
        lines.append("|---|---|---|---|---|")
        for f in agents:
            desc = get_frontmatter_field(f, "description") or "*no description*"
            model = get_frontmatter_field(f, "model") or "inherit"
            color = get_frontmatter_field(f, "color") or "—"
            lines.append(f"| `{f.stem}` | {desc} | {model} | {color} | [{f.name}](.claude/agents/{f.name}) |")
    else:
        lines.append("*No agents found in `.claude/agents/`*")
    lines.append("")

    # ── Skills ───────────────────────────────────────────────────────────────
    skills_dir = CLAUDE_DIR / "skills"
    lines.append("### Skills")
    lines.append("")
    skills = sorted(skills_dir.glob("*.md")) if skills_dir.exists() else []
    if skills:
        lines.append("| Skill | Description | File |")
        lines.append("|---|---|---|")
        for f in skills:
            name = get_frontmatter_field(f, "name") or f.stem
            desc = get_frontmatter_field(f, "description") or "*no description*"
            lines.append(f"| **{name}** | {desc} | [{f.name}](.claude/skills/{f.name}) |")
    else:
        lines.append("*No skills found in `.claude/skills/`*")
    lines.append("")

    # ── Hooks ────────────────────────────────────────────────────────────────
    hooks_dir = CLAUDE_DIR / "hooks"
    lines.append("### Hooks")
    lines.append("")
    hook_scripts = {
        "pre_bash_guard.py":     ("PreToolUse → Bash",          "Blocks dangerous bash commands before execution"),
        "post_bash_logger.py":   ("PostToolUse → Bash",         "Logs every bash command to session audit trail"),
        "session_summary.py":    ("Stop",                       "Prints session summary when Claude Code closes"),
        "update_claude_docs.py": ("PostToolUse → Write/Edit",   "Regenerates this inventory when .claude/ files change"),
    }
    hooks = sorted(hooks_dir.glob("*.py")) if hooks_dir.exists() else []
    if hooks:
        lines.append("| Script | Event | Purpose | Lines |")
        lines.append("|---|---|---|---|")
        for f in hooks:
            event, purpose = hook_scripts.get(f.name, ("—", "*see file*"))
            lc = file_line_count(f)
            lines.append(f"| [`{f.name}`](.claude/hooks/{f.name}) | {event} | {purpose} | {lc} |")
    else:
        lines.append("*No hook scripts found in `.claude/hooks/`*")
    lines.append("")

    # ── Summary counts ───────────────────────────────────────────────────────
    lines.append("### Summary")
    lines.append("")
    lines.append("| Type | Count |")
    lines.append("|---|---|")
    lines.append(f"| Slash commands | {len(commands)} |")
    lines.append(f"| Agents | {len(agents)} |")
    lines.append(f"| Skills | {len(skills)} |")
    lines.append(f"| Hook scripts | {len(hooks)} |")
    lines.append("")

    return "\n".join(lines)


# ── Docs Updater ─────────────────────────────────────────────────────────────

def update_docs():
    """Regenerate the inventory section inside claude-structure-docs.md."""
    if not DOCS_FILE.exists():
        print(f"[update_claude_docs] {DOCS_FILE} not found — skipping", file=sys.stderr)
        return

    content = DOCS_FILE.read_text(encoding="utf-8")

    start_idx = content.find(INVENTORY_START)
    end_idx = content.find(INVENTORY_END)

    if start_idx == -1 or end_idx == -1:
        print("[update_claude_docs] Inventory markers not found in docs file — skipping", file=sys.stderr)
        return

    inventory_content = build_inventory()
    new_section = f"{INVENTORY_START}\n\n{inventory_content}\n{INVENTORY_END}"
    updated = content[:start_idx] + new_section + content[end_idx + len(INVENTORY_END):]

    DOCS_FILE.write_text(updated, encoding="utf-8")
    print(f"[update_claude_docs] Updated {DOCS_FILE} at {datetime.now().strftime('%H:%M:%S')}")


# ── Hook Entry Point ──────────────────────────────────────────────────────────

def is_claude_dir_change(stdin_data: str) -> bool:
    """Check if the tool use was a Write/Edit on a file inside .claude/."""
    try:
        data = json.loads(stdin_data)
        tool_name = data.get("tool_name", "")
        if tool_name not in ("Write", "Edit", "MultiEdit"):
            return False
        tool_input = data.get("tool_input", {})
        file_path = ""
        if isinstance(tool_input, dict):
            file_path = tool_input.get("file_path", "")
        # Normalize separators for cross-platform matching
        normalized = file_path.replace("\\", "/")
        return "/.claude/" in normalized or normalized.endswith("/.claude")
    except Exception:
        return False


def main():
    # Allow manual regeneration: python update_claude_docs.py --regenerate
    if "--regenerate" in sys.argv:
        update_docs()
        return

    # Hook mode: read stdin, check if a .claude/ file changed
    try:
        raw = sys.stdin.read()
        if raw.strip() and is_claude_dir_change(raw):
            update_docs()
    except Exception as e:
        print(f"[update_claude_docs] Error: {e}", file=sys.stderr)


if __name__ == "__main__":
    main()
