# ── AI-Generated PySpark Script ───────────────────────────────────────────────
# Generated by: Claude Sonnet (claude-sonnet-4-6) via Gold Agent
# Pipeline:     gold_agent_performance_sla_audit
# Grain:        One row per agent (including agents with no tickets via FULL OUTER JOIN)
# Source tables: ticket_events_silver, pg_support_agents_silver
# ──────────────────────────────────────────────────────────────────────────────

import sys
from pathlib import Path

from pyspark.sql import SparkSession
from pyspark.sql import functions as F

spark = SparkSession.builder.appName("gold_agent_performance_sla_audit").getOrCreate()
spark.sparkContext.setLogLevel("WARN")

try:
    silver_path = Path("data/silver")

    # ── Load Silver tables ────────────────────────────────────────────────────
    tickets = spark.read.parquet(str(silver_path / "ticket_events_silver"))
    tickets = tickets.drop("_corrupt_record") if "_corrupt_record" in tickets.columns else tickets

    agents = spark.read.parquet(str(silver_path / "pg_support_agents_silver"))
    agents = agents.drop("_corrupt_record") if "_corrupt_record" in agents.columns else agents

    # ── FULL OUTER JOIN (string form auto-coalesces the key) ──────────────────
    df = tickets.join(agents, "agent_id", "full")

    # ── Pre-aggregation: derive dimension columns before groupBy ──────────────
    df = df.withColumn(
        "agent_full_name",
        F.when(F.col("agent_id") == 799, F.lit("AUTOMATED_BOT")).otherwise(
            F.concat_ws(" ", F.col("first_name"), F.col("last_name"))
        ),
    )
    df = df.withColumn(
        "support_tier",
        F.when(F.col("agent_id") == 799, F.lit("AI_AGENT")).otherwise(F.col("tier_level")),
    )

    # ── SLA breach flag (pre-aggregation) ─────────────────────────────────────
    sla_breach_cond = (
        (F.col("priority") == "Critical") & (F.col("response_time_minutes") > 15)
    ) | (
        (F.col("priority") == "High") & (F.col("response_time_minutes") > 30)
    ) | (
        (F.col("priority") == "Low") & (F.col("response_time_minutes") > 120)
    )

    # ── Aggregation ───────────────────────────────────────────────────────────
    result = df.groupBy("agent_id", "agent_full_name", "support_tier").agg(
        F.count("ticket_id").alias("total_tickets_assigned"),
        F.round(F.avg("response_time_minutes"), 2).alias("average_response_time_min"),
        F.sum(F.when(sla_breach_cond, 1).otherwise(0)).alias("sla_breach_count"),
        F.round(
            F.sum(F.when(F.col("resolved") == True, 1).otherwise(0))  # noqa: E712
            / F.count("ticket_id")
            * 100,
            2,
        ).alias("resolution_rate_percent"),
    )

    # ── Write Gold table ──────────────────────────────────────────────────────
    output_path = "data/gold/gold_agent_performance_sla_audit"
    result.coalesce(1).write.mode("overwrite").parquet(output_path)

    print("[Gold] SUCCESS: gold_agent_performance_sla_audit")
    sys.exit(0)

except Exception as e:
    print(f"[Gold] ERROR: {e}")
    sys.exit(1)
